version: "3.0"
services:
  influx:
    container_name: influx
    image: influxdb:latest
    env_file:
      - .env
    ports:
      - "8088:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    networks:
      - iot_net
    environment:
      - TZ=Europe/Zurich
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_MODE=${DOCKER_INFLUXDB_INIT_MODE}
      - INFLUXDB_HTTP_FLUX_ENABLED='true'
      - INFLUXDB_HTTP_AUTH_ENABLED='true'
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config/
      - ./mosquitto/log:/mosquitto/log/
      - mosquitto_data:/mosquitto/data
    expose:
      - "1883"
      - "9001"
      - "40002"
    networks:
      - iot_net
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
    - "3000:3000"
    env_file:
      - .env
    networks:
    - iot_net
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/config:/etc/grafana
  telegraf:
    image: telegraf
    links:
      - influx
    env_file:
      - .env
    volumes:
      - ./telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf
    environment: 
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    networks:
      - iot_net
volumes:
  influxdb-data:
  grafana-storage:
  mosquitto_data:

networks:
  iot_net:
